services:
  mysql:
    image: mysql:8.0.22
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "5300:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  hms_backend:
    build: .
    container_name: hms_backend
    restart: always
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_URL=${DB_URL}

    ports:
      - "8000:8000"
    depends_on:
      - mysql

    command: bash -c "alembic upgrade head && python initialize.py && uvicorn main:app --host 0.0.0.0"
