"""migration

Revision ID: 0fda2663e56e
Revises: 4d1603791dd6
Create Date: 2024-08-20 23:58:21.350670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0fda2663e56e'
down_revision: Union[str, None] = '4d1603791dd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=mysql.ENUM('pending', 'confirmed'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=mysql.ENUM('pending', 'confirmed'),
               nullable=True)
    # ### end Alembic commands ###
