"""migration

Revision ID: 410103fa13a8
Revises: a0a36f96972e
Create Date: 2024-08-26 23:19:27.616053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '410103fa13a8'
down_revision: Union[str, None] = 'a0a36f96972e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=mysql.ENUM('pending', 'confirmed', 'canceled'),
               nullable=False)
    op.alter_column('payments', 'transactionId',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('payments', 'paymentMethod',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('cash', 'mpesa', name='paymentenum'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'paymentMethod',
               existing_type=sa.Enum('cash', 'mpesa', name='paymentenum'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'transactionId',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=mysql.ENUM('pending', 'confirmed', 'canceled'),
               nullable=True)
    # ### end Alembic commands ###
