"""initial migration

Revision ID: 6fc455cd2f4d
Revises: 
Create Date: 2024-08-09 19:32:45.007929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6fc455cd2f4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new-users',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('admin', 'doctor', 'patient', 'pharmacy', name='role'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_new-users_email'), 'new-users', ['email'], unique=False)
    op.drop_index('email', table_name='attendance')
    op.drop_index('first_name', table_name='attendance')
    op.drop_index('last_name', table_name='attendance')
    op.drop_index('phone', table_name='attendance')
    op.drop_table('attendance')
    op.drop_index('email', table_name='customer')
    op.drop_index('username', table_name='customer')
    op.drop_table('customer')
    op.drop_index('fk_orders_product1_idx', table_name='orders')
    op.drop_index('fk_orders_users1_idx', table_name='orders')
    op.drop_table('orders')
    op.drop_index('fk_product_category1_idx', table_name='product')
    op.drop_index('fk_product_suppliers_idx', table_name='product')
    op.drop_table('product')
    op.drop_table('suppliers')
    op.drop_table('category')
    op.drop_index('email', table_name='user')
    op.drop_index('username', table_name='user')
    op.drop_table('user')
    op.drop_index('event_name', table_name='events')
    op.drop_table('events')
    op.drop_table('users')
    op.add_column('payments', sa.Column('transactionId', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('patientId', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('billingId', sa.Integer(), nullable=False))
    op.add_column('payments', sa.Column('createdAt', sa.DateTime(), nullable=True))
    op.alter_column('payments', 'paymentMethod',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'paymentDate',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('fk_payments_orders1_idx', table_name='payments')
    op.create_index(op.f('ix_payments_billingId'), 'payments', ['billingId'], unique=False)
    op.create_index(op.f('ix_payments_patientId'), 'payments', ['patientId'], unique=False)
    op.create_index(op.f('ix_payments_transactionId'), 'payments', ['transactionId'], unique=True)
    op.drop_constraint('fk_payments_orders1', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'patients', ['patientId'], ['patientId'])
    op.create_foreign_key(None, 'payments', 'billing', ['billingId'], ['billingId'])
    op.drop_column('payments', 'orderId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('orderId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('fk_payments_orders1', 'payments', 'orders', ['orderId'], ['orderId'])
    op.drop_index(op.f('ix_payments_transactionId'), table_name='payments')
    op.drop_index(op.f('ix_payments_patientId'), table_name='payments')
    op.drop_index(op.f('ix_payments_billingId'), table_name='payments')
    op.create_index('fk_payments_orders1_idx', 'payments', ['orderId'], unique=False)
    op.alter_column('payments', 'paymentDate',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('payments', 'paymentMethod',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=False)
    op.drop_column('payments', 'createdAt')
    op.drop_column('payments', 'billingId')
    op.drop_column('payments', 'patientId')
    op.drop_column('payments', 'transactionId')
    op.create_table('users',
    sa.Column('userId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phoneNumber', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=45), server_default=sa.text("'user'"), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('events',
    sa.Column('event_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('event_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('event_description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('event_date', mysql.DATETIME(), nullable=False),
    sa.Column('event_location', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('event_name', 'events', ['event_name'], unique=True)
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'user'), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'user', ['username'], unique=True)
    op.create_index('email', 'user', ['email'], unique=True)
    op.create_table('category',
    sa.Column('categoryId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('categoryName', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('categoryId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('suppliers',
    sa.Column('supplierId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('supplierName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('contactPerson', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('contactNumber', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('Address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('supplierId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('product',
    sa.Column('productId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('productName', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('productDescription', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('productPrice', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stocklevel', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supplierId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('categoryId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['categoryId'], ['category.categoryId'], name='fk_product_category1'),
    sa.ForeignKeyConstraint(['supplierId'], ['suppliers.supplierId'], name='fk_product_suppliers'),
    sa.PrimaryKeyConstraint('productId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_product_suppliers_idx', 'product', ['supplierId'], unique=False)
    op.create_index('fk_product_category1_idx', 'product', ['categoryId'], unique=False)
    op.create_table('orders',
    sa.Column('orderId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('productId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.VARCHAR(length=45), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('paymentStatus', mysql.VARCHAR(length=10), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('createdAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updatedAt', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['productId'], ['product.productId'], name='fk_orders_product1'),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name='fk_orders_users1'),
    sa.PrimaryKeyConstraint('orderId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('fk_orders_users1_idx', 'orders', ['userId'], unique=False)
    op.create_index('fk_orders_product1_idx', 'orders', ['productId'], unique=False)
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'user'), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'customer', ['username'], unique=True)
    op.create_index('email', 'customer', ['email'], unique=True)
    op.create_table('attendance',
    sa.Column('attendance_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('event_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], name='attendance_ibfk_1'),
    sa.PrimaryKeyConstraint('attendance_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('phone', 'attendance', ['phone'], unique=True)
    op.create_index('last_name', 'attendance', ['last_name'], unique=True)
    op.create_index('first_name', 'attendance', ['first_name'], unique=True)
    op.create_index('email', 'attendance', ['email'], unique=True)
    op.drop_index(op.f('ix_new-users_email'), table_name='new-users')
    op.drop_table('new-users')
    # ### end Alembic commands ###
