"""Initial migration

Revision ID: 7d0f97328866
Revises: 
Create Date: 2024-08-15 20:52:15.921643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0f97328866'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctors',
    sa.Column('doctorId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phoneNumber', sa.String(length=50), nullable=False),
    sa.Column('speciality', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('doctorId')
    )
    op.create_index(op.f('ix_doctors_email'), 'doctors', ['email'], unique=False)
    op.create_table('new-users',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('admin', 'doctor', 'patient', 'pharmacy', name='role'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_new-users_email'), 'new-users', ['email'], unique=False)
    op.create_table('patients',
    sa.Column('patientId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('dateOfBirth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('address', sa.String(length=20), nullable=False),
    sa.Column('phoneNumber', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('emergencyNumber', sa.String(length=20), nullable=False),
    sa.Column('insuranceNumber', sa.String(length=20), nullable=False),
    sa.Column('insuranceName', sa.String(length=50), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('patientId')
    )
    op.create_index(op.f('ix_patients_email'), 'patients', ['email'], unique=False)
    op.create_table('prescription',
    sa.Column('prescriptionId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prescriptionName', sa.String(length=50), nullable=False),
    sa.Column('dosage', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.String(length=10), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('prescriptionId')
    )
    op.create_table('appointments',
    sa.Column('appointmentId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('appointmentDate', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', name='appointmentenum'), nullable=True),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('doctorId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctors.doctorId'], ),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], ),
    sa.PrimaryKeyConstraint('appointmentId')
    )
    op.create_index(op.f('ix_appointments_doctorId'), 'appointments', ['doctorId'], unique=False)
    op.create_index(op.f('ix_appointments_patientId'), 'appointments', ['patientId'], unique=False)
    op.create_table('billing',
    sa.Column('billingId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('billingDate', sa.Date(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], ),
    sa.PrimaryKeyConstraint('billingId')
    )
    op.create_index(op.f('ix_billing_patientId'), 'billing', ['patientId'], unique=False)
    op.create_table('medication',
    sa.Column('medicationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnosis', sa.String(length=255), nullable=False),
    sa.Column('treatment', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('prescriptionId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], ),
    sa.ForeignKeyConstraint(['prescriptionId'], ['prescription.prescriptionId'], ),
    sa.PrimaryKeyConstraint('medicationId')
    )
    op.create_index(op.f('ix_medication_patientId'), 'medication', ['patientId'], unique=False)
    op.create_index(op.f('ix_medication_prescriptionId'), 'medication', ['prescriptionId'], unique=False)
    op.create_table('payments',
    sa.Column('paymentId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transactionId', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('paymentMethod', sa.String(length=20), nullable=False),
    sa.Column('paymentDate', sa.DateTime(), nullable=False),
    sa.Column('patientId', sa.Integer(), nullable=False),
    sa.Column('billingId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['billingId'], ['billing.billingId'], ),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], ),
    sa.PrimaryKeyConstraint('paymentId')
    )
    op.create_index(op.f('ix_payments_billingId'), 'payments', ['billingId'], unique=False)
    op.create_index(op.f('ix_payments_patientId'), 'payments', ['patientId'], unique=False)
    op.create_index(op.f('ix_payments_transactionId'), 'payments', ['transactionId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_transactionId'), table_name='payments')
    op.drop_index(op.f('ix_payments_patientId'), table_name='payments')
    op.drop_index(op.f('ix_payments_billingId'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_medication_prescriptionId'), table_name='medication')
    op.drop_index(op.f('ix_medication_patientId'), table_name='medication')
    op.drop_table('medication')
    op.drop_index(op.f('ix_billing_patientId'), table_name='billing')
    op.drop_table('billing')
    op.drop_index(op.f('ix_appointments_patientId'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_doctorId'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('prescription')
    op.drop_index(op.f('ix_patients_email'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_new-users_email'), table_name='new-users')
    op.drop_table('new-users')
    op.drop_index(op.f('ix_doctors_email'), table_name='doctors')
    op.drop_table('doctors')
    # ### end Alembic commands ###
