"""migration

Revision ID: 80d60e515e11
Revises: b8ae0cfc7a57
Create Date: 2024-08-29 17:34:14.609217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '80d60e515e11'
down_revision: Union[str, None] = 'b8ae0cfc7a57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'mpesaRef')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('mpesaRef', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
