"""Initial migration

Revision ID: 893e1a7c9a0c
Revises: 7d0f97328866
Create Date: 2024-08-15 21:17:02.523437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '893e1a7c9a0c'
down_revision: Union[str, None] = '7d0f97328866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new_users',
    sa.Column('userId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=False),
    sa.Column('lastName', sa.String(length=50), nullable=False),
    sa.Column('role', sa.Enum('admin', 'doctor', 'patient', 'pharmacy', name='role'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_new_users_email'), 'new_users', ['email'], unique=False)
    op.drop_index('ix_new-users_email', table_name='new-users')
    op.drop_table('new-users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new-users',
    sa.Column('userId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'doctor', 'patient', 'pharmacy'), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_new-users_email', 'new-users', ['email'], unique=False)
    op.drop_index(op.f('ix_new_users_email'), table_name='new_users')
    op.drop_table('new_users')
    # ### end Alembic commands ###
