"""migration

Revision ID: a0a36f96972e
Revises: 5f3249a0789f
Create Date: 2024-08-21 00:51:16.586412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a0a36f96972e'
down_revision: Union[str, None] = '5f3249a0789f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointments', 'status',
               existing_type=mysql.ENUM('pending', 'confirmed','canceled'),
               nullable=True)
    op.alter_column('billing', 'status',
               existing_type=mysql.ENUM('pending', 'paid'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing', 'status',
               existing_type=mysql.ENUM('pending', 'paid'),
               nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=mysql.ENUM('pending', 'confirmed'),
               nullable=False)
    # ### end Alembic commands ###
