"""migration

Revision ID: a363691f54b8
Revises: dfbb4a100bca
Create Date: 2024-08-29 16:04:56.514664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a363691f54b8'
down_revision: Union[str, None] = 'dfbb4a100bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('phoneNumber', sa.String(length=100), nullable=False))
    op.alter_column('payments', 'transactionId',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'transactionId',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_column('payments', 'phoneNumber')
    # ### end Alembic commands ###
