"""Initial migration

Revision ID: af5ee0a08029
Revises: 3de56cb27dc5
Create Date: 2024-08-07 11:14:37.088853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af5ee0a08029'
down_revision = '3de56cb27dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('doctorId', table_name='appointments')
    op.drop_index('patientId', table_name='appointments')
    op.drop_table('appointments')
    op.drop_table('users')
    op.drop_index('doctorId', table_name='prescription')
    op.drop_index('patientId', table_name='prescription')
    op.drop_table('prescription')
    op.drop_index('doctorId', table_name='medication')
    op.drop_index('patientId', table_name='medication')
    op.drop_table('medication')
    op.drop_table('patients')
    op.drop_table('doctors')
    op.drop_index('patientId', table_name='billing')
    op.drop_table('billing')
    op.drop_index('billingId', table_name='payments')
    op.drop_index('patientId', table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('paymentId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transactionId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paymentMethod', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('paymentDate', mysql.DATETIME(), nullable=False),
    sa.Column('patientId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('billingId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['billingId'], ['billing.billingId'], name='payments_ibfk_2'),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], name='payments_ibfk_1'),
    sa.PrimaryKeyConstraint('paymentId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('patientId', 'payments', ['patientId'], unique=True)
    op.create_index('billingId', 'payments', ['billingId'], unique=True)
    op.create_table('billing',
    sa.Column('billingId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('billingDate', sa.DATE(), nullable=False),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('patientId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], name='billing_ibfk_1'),
    sa.PrimaryKeyConstraint('billingId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('patientId', 'billing', ['patientId'], unique=True)
    op.create_table('doctors',
    sa.Column('doctorId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phoneNumber', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('speciality', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('doctorId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('patients',
    sa.Column('patientId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dateOfBirth', sa.DATE(), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('address', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('phoneNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('emergencyNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('insuranceNumber', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('insuranceName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('patientId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('medication',
    sa.Column('medicationIid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('diagnosis', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('treatment', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('notes', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('recordDate', mysql.DATETIME(), nullable=False),
    sa.Column('patientId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctorId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['doctorId'], ['doctors.doctorId'], name='medication_ibfk_2'),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], name='medication_ibfk_1'),
    sa.PrimaryKeyConstraint('medicationIid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('patientId', 'medication', ['patientId'], unique=True)
    op.create_index('doctorId', 'medication', ['doctorId'], unique=True)
    op.create_table('prescription',
    sa.Column('prescriptionId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('prescriptionName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('dosage', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('instructions', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('prescriptionDate', sa.DATE(), nullable=False),
    sa.Column('patientId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctorId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctors.doctorId'], name='prescription_ibfk_2'),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], name='prescription_ibfk_1'),
    sa.PrimaryKeyConstraint('prescriptionId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('patientId', 'prescription', ['patientId'], unique=True)
    op.create_index('doctorId', 'prescription', ['doctorId'], unique=True)
    op.create_table('users',
    sa.Column('userId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('lastName', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('role', mysql.ENUM('admin', 'doctor', 'patient', 'pharmacy'), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('userId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('appointments',
    sa.Column('appointmentId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointmentDate', sa.DATE(), nullable=False),
    sa.Column('reason', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.ENUM('pending', 'confirmed'), nullable=True),
    sa.Column('patientId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('doctorId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdAt', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['doctorId'], ['doctors.doctorId'], name='appointments_ibfk_2'),
    sa.ForeignKeyConstraint(['patientId'], ['patients.patientId'], name='appointments_ibfk_1'),
    sa.PrimaryKeyConstraint('appointmentId'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('patientId', 'appointments', ['patientId'], unique=True)
    op.create_index('doctorId', 'appointments', ['doctorId'], unique=True)
    # ### end Alembic commands ###
