"""migration

Revision ID: dfbb4a100bca
Revises: 410103fa13a8
Create Date: 2024-08-29 15:30:37.061737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'dfbb4a100bca'
down_revision: Union[str, None] = '410103fa13a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_req_id', sa.String(length=100), nullable=True),
    sa.Column('phone_no', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('mpesa_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_merchant_req_id'), 'transactions', ['merchant_req_id'], unique=True)
    op.add_column('payments', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('payments', sa.Column('mpesaRef', sa.String(length=100), nullable=True))
    op.alter_column('payments', 'transactionId',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=100),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'transactionId',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=10),
               nullable=True)
    op.drop_column('payments', 'mpesaRef')
    op.drop_column('payments', 'status')
    op.drop_index(op.f('ix_transactions_merchant_req_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
