"""migration

Revision ID: e0f5f709ee24
Revises: f55a8d0aae6a
Create Date: 2024-08-09 12:15:10.315787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e0f5f709ee24'
down_revision: Union[str, None] = 'f55a8d0aae6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medication', 'recordDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medication', sa.Column('recordDate', mysql.DATETIME(), nullable=False))
    # ### end Alembic commands ###
