"""migration

Revision ID: f3ded14731ff
Revises: 80d60e515e11
Create Date: 2024-08-29 22:17:01.527250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f3ded14731ff'
down_revision: Union[str, None] = '80d60e515e11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'merchant_req_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index('ix_transactions_transactionId', table_name='transactions')
    op.drop_index('ix_transactions_merchant_req_id', table_name='transactions')
    op.create_index(op.f('ix_transactions_merchant_req_id'), 'transactions', ['merchant_req_id'], unique=False)
    op.drop_column('transactions', 'transactionId')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('transactionId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_transactions_merchant_req_id'), table_name='transactions')
    op.create_index('ix_transactions_merchant_req_id', 'transactions', ['merchant_req_id'], unique=True)
    op.create_index('ix_transactions_transactionId', 'transactions', ['transactionId'], unique=False)
    op.alter_column('transactions', 'merchant_req_id',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
