"""migration

Revision ID: f55a8d0aae6a
Revises: 60948a7ed2e5
Create Date: 2024-08-09 11:18:01.981776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55a8d0aae6a'
down_revision: Union[str, None] = '60948a7ed2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription', sa.Column('duration', sa.String(length=10), nullable=False))
    op.drop_column('prescription', 'prescriptionDate')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prescription', sa.Column('prescriptionDate', sa.DATE(), nullable=False))
    op.drop_column('prescription', 'duration')
    # ### end Alembic commands ###
